name: AutoRelease

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Find and Extract .jar from ZIP
        run: |
          ZIP_FILE=$(find . -type f -name "*.zip")
          echo "Found ZIP file: $ZIP_FILE"
          unzip -j "$ZIP_FILE" "*.jar" -d ./extracted
          ls -l ./extracted

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: "latest" # You can use a fixed name or format
          release_name: "Release latest"
          body: |
            Changes in this release:
            - Add your changes here
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./extracted/*.jar
          asset_name: $(basename ./extracted/*.jar)
          asset_content_type: application/java-archive