name: Release

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Checkout code
        uses: actions/checkout@v4.1.7
      
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '20'
      
      - name: Install npm 5 or later
        run: npm install -g npm@10.8.1
      
      - name: Make gradlew executable
        run: chmod +x gradlew
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: ./gradlew build
      
      - name: Run semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
